### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by oldirtybasti** [NVIDIA/ansible-role-nvidia-driver#15]
Is there support for Ubuntu 20.04 planned? The role currently cannot be installed on the latest ubuntu.

**Comment by dplessas** [comment]
I am adding my vote of this as well. We can code around this, but if we are doing that what is the point of this project?

**Comment by ajdecon** [comment]
Ubuntu 20.04 packages are now included in the package repositories that this role uses. I've tested and verified that I can install the driver on a 20.04 system. This should now be good to go.
