### ISSUE TITLE
Kernel kernel-devel mismatch on non updated systems breaks dkms and module load

### ISSUE THREAD

**Issue by aspeer06** [NVIDIA/ansible-role-nvidia-driver#18]
After running playbook I ended up with a non working driver and this:

Installed Packages
kernel.x86_64                            3.10.0-957.el7                                  @anaconda
kernel-debug-devel.x86_64        3.10.0-1127.18.2.el7                            @updates
kernel-devel.x86_64                   3.10.0-1127.18.2.el7                            @updates
kernel-headers.x86_64               3.10.0-957.el7                                  @anaconda
kernel-tools.x86_64                    3.10.0-957.el7                                  @anaconda
kernel-tools-libs.x86_64             3.10.0-957.el7                                  @anaconda

Might be good to install the kernel headers/devel for the running kernel on systems that require specific kernel versions? 
Note: updating to the newer kernel did fix the issue as I assume downgrading headers/devel would have as well

**Comment by ajdecon** [comment]
Should be fixed by #21
