### ISSUE TITLE
New drivers are not published to repository

### ISSUE THREAD

**Issue by salanki** [NVIDIA/ansible-role-nvidia-driver#2]
Hello,

The latest 430 drivers are not published to the NVIDIA developer repository. The Ubuntu repository used by this role, `http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/` only contains up to driver version 410.

**Comment by ajdecon** [comment]
This git repo only provides an Ansible role for installing the NVIDIA driver using package management tools, and doesn't cover the package repository itself. So I'm closing this issue as out of scope.

FWIW, the NVIDIA [driver download tool](https://www.nvidia.com/Download/index.aspx) recommends driver 418.87 for Tesla GPUs on Linux, and this version is included in the Ubuntu repository.

**Comment by salanki** [comment]
Ok, sure, but for whoever needs the newest driver (ie. due to software requirements) it is useless. Would be nice if a NVIDIA supplied role supported all NVIDIA released stable drivers out of the box.

For reference, `uchida.nvidia-driver` supports the PPA repo out of the box which is up to date with the latest releases.
