### ISSUE TITLE
"Running reboot with local connection would reboot the control node."

### ISSUE THREAD

**Issue by vielmetti** [NVIDIA/ansible-role-nvidia-driver#20]
I've downloaded this role through Galaxy and am attempting to get Rapids.AI installed.

I've created a file nvidia-driver.yml

```
---
- hosts: localhost
  roles: 
  - nvidia.nvidia_driver
```

and execute it with `ansible-playbook nvidia-driver.yml`. When it runs, the last command ( a reboot instruction ) fails with

"Running reboot with local connection would reboot the control node."

Rebooting the system, and running the playbook again, returns success.

Now my questions:

* Can the README be extended to say something about use of
this module? I am just familiar enough with Ansible to be dangerous,
but Galaxy was new to me, and I ended up referring to this simple
tutorial at https://www.jeffgeerling.com/blog/using-ansible-galaxy to
make forward progress.
* Is there a straightforward way to determine whether the install
was successful? A verification step would be helpful.

thanks

**Comment by vielmetti** [comment]
Answering my own question, one useful tool for verifying correct installation
is `nvidia-smi`. 

When I followed just these instructions on Ubuntu 18.04, I did not get a succcessful
install; but when I added `sudo apt-get install linux-headers-$(uname -r)` things 
started to work.

**Comment by ajdecon** [comment]
@vielmetti : Please take a look at the updated README and let us know if there are any other questions it should answer! https://github.com/NVIDIA/ansible-role-nvidia-driver/blob/master/README.md

**Comment by vielmetti** [comment]
Thanks @ajdecon for the updated docs - this looks pretty complete.

**Comment by vielmetti** [comment]
Closed by #22 .
