### ISSUE TITLE
Use DKMS drivers as default, or provide an option to do that.

### ISSUE THREAD

**Issue by antoniomo** [NVIDIA/ansible-role-nvidia-driver#6]
Maybe related to #4.

Here https://github.com/NVIDIA/ansible-role-nvidia-driver/blob/master/tasks/install-redhat.yml#L21 it is installing the `cuda-drivers` meta-package, which points to the non-dkms packages. In the repo (for example https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/) there are `-dkms` versions for the nvidia and cuda latest drivers. Installing non-dkms versions is brittle, because any kernel update requires re-running this playbook or getting broken drivers, something that is non-obvious.

Either using DKMS drivers by default, or providing an option to do just that, would be useful. We can fix it by installing those -dkms individual packages by hand, but an nvidia-maintained playbook or DKMS metapackage would prevent that solution from breaking in the future.

**Comment by ajdecon** [comment]
DKMS packages should be installed by default now:

* #10 changes the role to install the DKMS packages on CentOS/RHEL.
* I confirmed that under Ubuntu, the `cuda-drivers` meta-package pulls in the most recent DKMS package `nvidia-dkms-440`.

On both distros, I tested by installing, performing a kernel upgrade, and rebooting. In each case, the driver rebuilt properly and was online following the reboot.

Closing this issue as fixed, but please re-open if you see any problems moving forward!
