### ISSUE TITLE
How to know the correct versions for nvidia_driver_branch and nvidia_driver_package_version

### ISSUE THREAD

**Issue by jaepetto** [NVIDIA/ansible-role-nvidia-driver#73]
Hi,

I'm currently trying to deploy the nvidia drivers as well as the nvidia CUDA toolkit using this Ansible playbook on Ubuntu 22.04 machines.

First, I'm not quite sure the impact of the `nvidia_driver_ubuntu_install_from_cuda_repo` flag. Aside from using different repositories to install the package, what would the use case to choose one option or the other?

I managed to install the drivers with the `nvidia_driver_branch: '525'`. Previously, we were using the `nvidia_driver_branch: '515'` option. How do I know which values are available?

Finally, what is the difference with the `nvidia_driver_package_version` version? Again, how do I know which values are available?

Thanks in advance for your help.

Emmanuel

**Comment by dholt** [comment]
Whether you install from the CUDA repos or the Ubuntu repos typically just depends on whether there is an older/newer/different version of the driver on the CUDA repos that wouldn't be available on the Ubuntu repos.

To find out which versions are available you can run `apt-cache madison cuda-drivers` on Ubuntu, or search the repos online:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=nvidia&searchon=names

**Comment by jaepetto** [comment]
Thanks @dholt
